    global:
      resolve_timeout: 2m
      wechat_api_url: 'https://qyapi.weixin.qq.com/cgi-bin/'
      wechat_api_secret: '<wechat_api_secret>'
      wechat_api_corp_id: 'ww9dbfed83582c0e44'

    route:
      group_by: ['alertname']
      group_wait: 15s
      group_interval: 15s
      repeat_interval: 15s
      receiver: 'wechat'
    receivers:
    - name: 'wechat'
      wechat_configs:
      - send_resolved: true
        #to_party: '1'
        to_user: '@all'
        agent_id: '1000002'
        api_secret: '<wechat_api_secret>'
        corp_id: 'ww9dbfed83582c0e44'
